version: "3.8"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/dockerfiles/nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: ${APP_NAME}_nginx
        expose:
            - "80/tcp"
        ports:
            - "8008:80"
        volumes:
            - ./docker/configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/html:delegated
        depends_on:
            - php
            - postgres
        networks:
            - test_rest

    php:
        build:
            context: .
            dockerfile: docker/dockerfiles/php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - test_rest

    postgres:
        image: postgres:latest
        container_name: ${APP_NAME}_postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - ./docker/database:/var/lib/postgresql/data
        networks:
            - test_rest

    pgadmin:
        image: dpage/pgadmin4
        container_name: ${APP_NAME}_pgadmin
        restart: always
        expose:
            - "80/tcp"
        ports:
            - "8088:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
        networks:
            - test_rest

    npm:
        image: node:current-alpine
        container_name: ${APP_NAME}_npm
        volumes:
            - ./:/var/www/html
        expose:
            - "3000/tcp"
            - "3001/tcp"
            - "5173/tcp"
        ports:
            - "3000:3000"
            - "3001:3001"
            - "5173:5173"
        working_dir: /var/www/html
        entrypoint: [ 'npm' ]
        networks:
            - test_rest

networks:
    test_rest:
        name: test_rest
        driver: bridge
